mode: 'debug'
board_data_location: 'K:\Coding\Golang\ricochet-robot-solver\board_data.json'

modes:
  default:
    node_neighbors: false
    board_states: false

  debug:
    node_neighbors: true
    board_states: true