mode: 'debug'
board_data_location: 'K:\Coding\Golang\ricochet-robot-solver\board_data.json'

modes:
  default:
    output:
      node_neighbors: false
      board_states: false

  debug:
    output:
      node_neighbors: true
      board_states: true