mode: 'debug'
board_data_location: 'K:\Coding\Golang\ricochet-robot-solver\tests\data\3b.json'

modes:
  default:
    output:
      node_neighbors: false
      board_states: false
      robot_stopping_positions: false

  debug:
    output:
      node_neighbors: true
      board_states: true
      robot_stopping_positions: true